name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_identityapp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_USERNAME: ${{ secrets.HEROKU_USERNAME }} 
        APP_NAME: ${{ secrets.APP_NAME }}
      run: |
        cd ./
        docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
